version: 2
jobs:
  build:
    working_directory: /go/src/github.com/dcarley/adventofcode-2017
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
